### ISSUE TITLE
[bug]Echo Issue on Specific Android 14 Devices Using LiveKit

### ISSUE THREAD

**Issue by yuemenglong** [livekit/client-sdk-flutter#678]
Hello, thank you for your excellent open-source project!

I encountered an issue while using it: on certain devices, an echo occurs during communication. The problematic devices identified so far are OnePlus 11 and Redmi Note 13, both running Android 14.

The specific issue is as follows:

When the problematic devices communicate with other phones using LiveKit for voice calls, the other party hears an echo from the problematic devices. However, the problematic devices themselves sound normal (this occurs regardless of whether it’s audio-only or video, or whether speaker mode is enabled).
Our app also supports WebRTC direct calls (bypassing LiveKit). We use the WebRTC client library included in the LiveKit SDK. In this scenario, communication is normal on these devices.
An even stranger issue arises: if the problematic devices first use WebRTC direct calling (scenario 2), everything works fine. However, once they use LiveKit for communication, subsequent WebRTC direct calls also produce echoes. Killing the process on the problematic devices restores normal behavior for WebRTC direct calls, but killing the process on the other side does not resolve the issue.

The software versions in use are:
client-sdk-flutter: 2.2.6
flutter-webrtc (the WebRTC client library included with the LiveKit SDK): 0.11.7

I currently have no clue how to resolve this issue. Could you please help investigate? Thank you!

**Comment by cloudwebrtc** [comment]
It sounds like the system audio mode has been changed when calling the livekit sdk

**Comment by fpasalioglu** [comment]
I have similar problems with some devices;
When someone using a **Samsung A70** device turns on their own microphone while someone else in the room has their microphone turned on, there is an echo. It can be said that the system audio mode has been changed.

For people using **Redmi Note 10 Pro, Redmi Note 9 Pro, Poco X3 Pro** devices, if there is no one else in the room with their microphone turned on, the sound of that person reaches the audience at a low volume. If someone in the room turns on the microphone, the voices of those using these devices start to be heard normally.

**Comment by Zoomtod** [comment]
> I have similar problems with some devices; When someone using a **Samsung A70** device turns on their own microphone while someone else in the room has their microphone turned on, there is an echo. It can be said that the system audio mode has been changed.
> 
> For people using **Redmi Note 10 Pro, Redmi Note 9 Pro, Poco X3 Pro** devices, if there is no one else in the room with their microphone turned on, the sound of that person reaches the audience at a low volume. If someone in the room turns on the microphone, the voices of those using these devices start to be heard normally.

Have you found any solution yet?

**Comment by skiffer-git** [comment]
I have similar problems with some devices

**Comment by Zoomtod** [comment]
Please share solution if found

**Comment by cloudwebrtc** [comment]
related fix https://github.com/flutter-webrtc/flutter-webrtc/pull/1808

**Comment by khushmadodiya** [comment]
Still getting same issue

**Comment by cloudwebrtc** [comment]
hi @khushmadodiya , what device model are you using?

**Comment by khushmadodiya** [comment]
S24 Ultra

**Comment by cloudwebrtc** [comment]
I believe this has been fixed in the latest version
https://pub.dev/packages/livekit_client/changelog

**Comment by Zoomtod** [comment]
I as well did upgraded to latest version
But the issue remains the same

**Comment by cloudwebrtc** [comment]
hi @Zoomtod, @khushmadodiya  Can you record a video when the echo occurs? And capture the logcat at that time?

I fixed the echo issue in S25U. It was caused by setPreferredInputDevice interrupting the built-in HW AEC processing, which caused the echo. Normally, the built-in HW echo cancellation in Android will work well.

**Comment by khushmadodiya** [comment]
I am using the latest version

**Comment by cloudwebrtc** [comment]
Added PR for automatically configure audio mode for Android,  This helps avoid echo caused by incorrect mode settings.
https://github.com/livekit/client-sdk-flutter/pull/746

Please continue to give us feedback if you have any improvements or issues.

**Comment by khushmadodiya** [comment]
This is my log and I have true all property in audioOption() and this logs
are showing and echo is not canceling in new model phone like galaxy s24


2025-04-11 00:49:28.782  6489-6489  org.webrtc.Logging      com.zoomtod.dhs
                     I  JavaAudioDeviceModule: setNoiseSuppressorEnabled:
true
2025-04-11 00:49:28.782  6489-6489  org.webrtc.Logging      com.zoomtod.dhs
                     W  WebRtcAudioRecordExternal:
SetNoiseSuppressorEnabled(true)
2025-04-11 00:49:28.782  6489-6489  org.webrtc.Logging      com.zoomtod.dhs
                     E  WebRtcAudioEffectsExternal: Attempting to enable or
disable nonexistent NoiseSuppressor.
2025-04-11 00:49:33.485  6489-6489  FlutterWebRTCPlugin     com.zoomtod.dhs
                     I  getUserMedia(audio): mandatory: [], optional:
[echoCancellation: true, noiseSuppression: true, autoGainControl: true,
voiceIsolation: true, googDAEchoCancellation: true, googEchoCancellation:
true, googEchoCancellation2: true, googNoiseSuppression: true,
googNoiseSuppression2: true, googAutoGainControl: true, googHighpassFilter:
true, googTypingNoiseDetection: true]
2025-04-11 00:49:34.278  6489-6773  org.webrtc.Logging      com.zoomtod.dhs
                     I  WebRtcAudioEffectsExternal: NoiseSuppressor: was
disabled, enable: true, is now: enabled

2025-04-11 00:49:33.485  6489-6489  FlutterWebRTCPlugin     com.zoomtod.dhs
                     I  getUserMedia(audio): mandatory: [], optional:
[echoCancellation: true, noiseSuppression: true, autoGainControl: true,
voiceIsolation: true, googDAEchoCancellation: true, googEchoCancellation:
true, googEchoCancellation2: true, googNoiseSuppression: true,
googNoiseSuppression2: true, googAutoGainControl: true, googHighpassFilter:
true, googTypingNoiseDetection: true]
2025-04-11 00:49:34.275  6489-6773  org.webrtc.Logging      com.zoomtod.dhs
                     I  WebRtcAudioEffectsExternal: AcousticEchoCanceler:
was enabled, enable: true, is now: enabled
2025-04-11 00:50:40.661  1923-8564  Telecom                 system_server
                     D  SamsungEchoLocateImsRegistrationAdapterImpl1 :
onRegistered imsRegistration:
***@***.***
2025-04-11 00:50:40.661  1923-8564  Telecom                 system_server
                     D  SamsungEchoLocateImsRegistrationAdapterImpl1 :
onRegistered imsRegistration: MMTEL_VOICE

**Comment by Zoomtod** [comment]
Here are the attatched patch of logs when i tried turning off and turning
on the mic triggering audio processing options

**Comment by Abdullah-319** [comment]
I am using livekit_client: ^2.5.1 but still i get echo issues
